# https://prometheus.io/docs/alerting/latest/configuration/
global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3h
  receiver: 'gmail-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: '@<login>gmail.com'
        from: '<login>@gmail.com'
        smarthost: smtp.gmail.com:587
        auth_username: '<login>@gmail.com'
        auth_identity: '<login>@gmail.com'
        auth_password: 'google-app-password' # example -> 'uiptpkzynxujrenb'
        send_resolved: true
